name: minimalist_state
description: A minimal state management solution.
version: 0.0.1
repository: https://github.com/Yoeri-z/minimalist_state

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
